version: '3.8'
services:
  todosDatabase:
    container_name: todos_database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - todosDatabaseData:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todosdatabase
      - POSTGRES_DATABASE=todosdatabase

volumes:
  todosDatabaseData: